package swimmingcompetition.networking.json;


public enum RequestType {
    LOGIN, LOGOUT, FINDING_ACCOUNT, GET_ALL_CHALLENGES,
    FINDING_ALL_PARTICIPANTS_BY_CHALLENGE,
    ADD_PARTICIPANT, ADD_PARTICIPANT_TO_MORE_CHALLENGES;
}
