package swimmingcompetition.networking.json;


public enum ResponseType {
    OK,ERROR,FINDING_ACCOUNT,GET_ALL_CHALLENGES,
    FINDING_ALL_PARTICIPANTS_BY_CHALLENGE,
    ADD_PARTICIPANT, ADD_PARTICIPANT_TO_MORE_CHALLENGES,
    UPDATE_TABLES;
}
