// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SwimmingCompetitionProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SwimmingCompetitionProtocol.proto</summary>
public static partial class SwimmingCompetitionProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for SwimmingCompetitionProtocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SwimmingCompetitionProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFTd2ltbWluZ0NvbXBldGl0aW9uUHJvdG9jb2wucHJvdG8iOwoJT3JnYW5p",
          "emVyEgoKAmlkGAEgASgDEhAKCHVzZXJuYW1lGAIgASgJEhAKCHBhc3N3b3Jk",
          "GAMgASgJIksKCUNoYWxsZW5nZRIKCgJpZBgBIAEoAxIbCghkaXN0YW5jZRgC",
          "IAEoDjIJLkRpc3RhbmNlEhUKBXN0eWxlGAMgASgOMgYuU3R5bGUiSwoLUGFy",
          "dGljaXBhbnQSCgoCaWQYASABKAMSDAoEbmFtZRgCIAEoCRILCgNhZ2UYAyAB",
          "KAUSFQoNY2hhbGxlbmdlX2lkcxgEIAMoAyJnCgxDaGFsbGVuZ2VEVE8SCgoC",
          "aWQYASABKAMSGwoIZGlzdGFuY2UYAiABKA4yCS5EaXN0YW5jZRIVCgVzdHls",
          "ZRgDIAEoDjIGLlN0eWxlEhcKD25vX3BhcnRpY2lwYW50cxgEIAEoBSJXCg5Q",
          "YXJ0aWNpcGFudERUTxIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEgsKA2Fn",
          "ZRgDIAEoBRIeCgpjaGFsbGVuZ2VzGAQgAygLMgouQ2hhbGxlbmdlIqgDCgdS",
          "ZXF1ZXN0EhsKBHR5cGUYASABKA4yDS5SZXF1ZXN0LlR5cGUSEAoIdXNlcm5h",
          "bWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkSHQoJb3JnYW5pemVyGAQgASgL",
          "MgouT3JnYW5pemVyEh0KCWNoYWxsZW5nZRgFIAEoCzIKLkNoYWxsZW5nZRIM",
          "CgRuYW1lGAYgASgJEgsKA2FnZRgHIAEoBRIhCgtwYXJ0aWNpcGFudBgIIAEo",
          "CzIMLlBhcnRpY2lwYW50Eh4KCmNoYWxsZW5nZXMYCSADKAsyCi5DaGFsbGVu",
          "Z2UivwEKBFR5cGUSCwoHVU5LTk9XThAAEgkKBUxPR0lOEAESCgoGTE9HT1VU",
          "EAISEwoPRklORElOR19BQ0NPVU5UEAMSFgoSR0VUX0FMTF9DSEFMTEVOR0VT",
          "EAQSKQolRklORElOR19BTExfUEFSVElDSVBBTlRTX0JZX0NIQUxMRU5HRRAF",
          "EhMKD0FERF9QQVJUSUNJUEFOVBAGEiYKIkFERF9QQVJUSUNJUEFOVF9UT19N",
          "T1JFX0NIQUxMRU5HRVMQByKUAwoIUmVzcG9uc2USHAoEdHlwZRgBIAEoDjIO",
          "LlJlc3BvbnNlLlR5cGUSHQoJb3JnYW5pemVyGAIgASgLMgouT3JnYW5pemVy",
          "EiEKCmNoYWxsZW5nZXMYAyADKAsyDS5DaGFsbGVuZ2VEVE8SJQoMcGFydGlj",
          "aXBhbnRzGAQgAygLMg8uUGFydGljaXBhbnREVE8SIQoLcGFydGljaXBhbnQY",
          "BSABKAsyDC5QYXJ0aWNpcGFudBINCgVlcnJvchgGIAEoCSLOAQoEVHlwZRIL",
          "CgdVTktOT1dOEAASBgoCT0sQARIJCgVFUlJPUhACEhMKD0ZJTkRJTkdfQUND",
          "T1VOVBADEhYKEkdFVF9BTExfQ0hBTExFTkdFUxAEEikKJUZJTkRJTkdfQUxM",
          "X1BBUlRJQ0lQQU5UU19CWV9DSEFMTEVOR0UQBRITCg9BRERfUEFSVElDSVBB",
          "TlQQBhImCiJBRERfUEFSVElDSVBBTlRfVE9fTU9SRV9DSEFMTEVOR0VTEAcS",
          "EQoNVVBEQVRFX1RBQkxFUxAIKlAKCERpc3RhbmNlEhgKFERJU1RBTkNFX1VO",
          "U1BFQ0lGSUVEEAASCAoETUlDQRABEggKBE1BUkUQAhIJCgVNRURJRRADEgsK",
          "B0VYVFJFTUEQBCpLCgVTdHlsZRIVChFTVFlMRV9VTlNQRUNJRklFRBAAEgkK",
          "BUxJQkVSEAESCQoFU1BBVEUQAhILCgdGTFVUVVJFEAMSCAoETUlYVBAEQkcK",
          "J3N3aW1taW5nY29tcGV0aXRpb24ubmV0d29ya2luZy5wcm90b2J1ZkIcU3dp",
          "bW1pbmdDb21wZXRpdGlvblByb3RvYnVmc2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Distance), typeof(global::Style), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Organizer), global::Organizer.Parser, new[]{ "Id", "Username", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Challenge), global::Challenge.Parser, new[]{ "Id", "Distance", "Style" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Participant), global::Participant.Parser, new[]{ "Id", "Name", "Age", "ChallengeIds" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ChallengeDTO), global::ChallengeDTO.Parser, new[]{ "Id", "Distance", "Style", "NoParticipants" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ParticipantDTO), global::ParticipantDTO.Parser, new[]{ "Id", "Name", "Age", "Challenges" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Type", "Username", "Password", "Organizer", "Challenge", "Name", "Age", "Participant", "Challenges" }, null, new[]{ typeof(global::Request.Types.Type) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Type", "Organizer", "Challenges", "Participants", "Participant", "Error" }, null, new[]{ typeof(global::Response.Types.Type) }, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// TO DO
/// </summary>
public enum Distance {
  [pbr::OriginalName("DISTANCE_UNSPECIFIED")] Unspecified = 0,
  [pbr::OriginalName("MICA")] Mica = 1,
  [pbr::OriginalName("MARE")] Mare = 2,
  [pbr::OriginalName("MEDIE")] Medie = 3,
  [pbr::OriginalName("EXTREMA")] Extrema = 4,
}

public enum Style {
  [pbr::OriginalName("STYLE_UNSPECIFIED")] Unspecified = 0,
  [pbr::OriginalName("LIBER")] Liber = 1,
  [pbr::OriginalName("SPATE")] Spate = 2,
  [pbr::OriginalName("FLUTURE")] Fluture = 3,
  [pbr::OriginalName("MIXT")] Mixt = 4,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Organizer : pb::IMessage<Organizer>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Organizer> _parser = new pb::MessageParser<Organizer>(() => new Organizer());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Organizer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Organizer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Organizer(Organizer other) : this() {
    id_ = other.id_;
    username_ = other.username_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Organizer Clone() {
    return new Organizer(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Organizer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Organizer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Organizer other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Challenge : pb::IMessage<Challenge>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Challenge> _parser = new pb::MessageParser<Challenge>(() => new Challenge());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Challenge> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Challenge() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Challenge(Challenge other) : this() {
    id_ = other.id_;
    distance_ = other.distance_;
    style_ = other.style_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Challenge Clone() {
    return new Challenge(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 2;
  private global::Distance distance_ = global::Distance.Unspecified;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Distance Distance {
    get { return distance_; }
    set {
      distance_ = value;
    }
  }

  /// <summary>Field number for the "style" field.</summary>
  public const int StyleFieldNumber = 3;
  private global::Style style_ = global::Style.Unspecified;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Style Style {
    get { return style_; }
    set {
      style_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Challenge);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Challenge other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Distance != other.Distance) return false;
    if (Style != other.Style) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Distance != global::Distance.Unspecified) hash ^= Distance.GetHashCode();
    if (Style != global::Style.Unspecified) hash ^= Style.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Style);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Style);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Style);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Challenge other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Distance != global::Distance.Unspecified) {
      Distance = other.Distance;
    }
    if (other.Style != global::Style.Unspecified) {
      Style = other.Style;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Distance = (global::Distance) input.ReadEnum();
          break;
        }
        case 24: {
          Style = (global::Style) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Distance = (global::Distance) input.ReadEnum();
          break;
        }
        case 24: {
          Style = (global::Style) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Participant : pb::IMessage<Participant>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Participant> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Participant() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Participant(Participant other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    age_ = other.age_;
    challengeIds_ = other.challengeIds_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Participant Clone() {
    return new Participant(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "age" field.</summary>
  public const int AgeFieldNumber = 3;
  private int age_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Age {
    get { return age_; }
    set {
      age_ = value;
    }
  }

  /// <summary>Field number for the "challenge_ids" field.</summary>
  public const int ChallengeIdsFieldNumber = 4;
  private static readonly pb::FieldCodec<long> _repeated_challengeIds_codec
      = pb::FieldCodec.ForInt64(34);
  private readonly pbc::RepeatedField<long> challengeIds_ = new pbc::RepeatedField<long>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<long> ChallengeIds {
    get { return challengeIds_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Participant);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Participant other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (Age != other.Age) return false;
    if(!challengeIds_.Equals(other.challengeIds_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Age != 0) hash ^= Age.GetHashCode();
    hash ^= challengeIds_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Age);
    }
    challengeIds_.WriteTo(output, _repeated_challengeIds_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Age);
    }
    challengeIds_.WriteTo(ref output, _repeated_challengeIds_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Age != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
    }
    size += challengeIds_.CalculateSize(_repeated_challengeIds_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Participant other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Age != 0) {
      Age = other.Age;
    }
    challengeIds_.Add(other.challengeIds_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Age = input.ReadInt32();
          break;
        }
        case 34:
        case 32: {
          challengeIds_.AddEntriesFrom(input, _repeated_challengeIds_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Age = input.ReadInt32();
          break;
        }
        case 34:
        case 32: {
          challengeIds_.AddEntriesFrom(ref input, _repeated_challengeIds_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ChallengeDTO : pb::IMessage<ChallengeDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ChallengeDTO> _parser = new pb::MessageParser<ChallengeDTO>(() => new ChallengeDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ChallengeDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChallengeDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChallengeDTO(ChallengeDTO other) : this() {
    id_ = other.id_;
    distance_ = other.distance_;
    style_ = other.style_;
    noParticipants_ = other.noParticipants_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChallengeDTO Clone() {
    return new ChallengeDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 2;
  private global::Distance distance_ = global::Distance.Unspecified;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Distance Distance {
    get { return distance_; }
    set {
      distance_ = value;
    }
  }

  /// <summary>Field number for the "style" field.</summary>
  public const int StyleFieldNumber = 3;
  private global::Style style_ = global::Style.Unspecified;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Style Style {
    get { return style_; }
    set {
      style_ = value;
    }
  }

  /// <summary>Field number for the "no_participants" field.</summary>
  public const int NoParticipantsFieldNumber = 4;
  private int noParticipants_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoParticipants {
    get { return noParticipants_; }
    set {
      noParticipants_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ChallengeDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ChallengeDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Distance != other.Distance) return false;
    if (Style != other.Style) return false;
    if (NoParticipants != other.NoParticipants) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Distance != global::Distance.Unspecified) hash ^= Distance.GetHashCode();
    if (Style != global::Style.Unspecified) hash ^= Style.GetHashCode();
    if (NoParticipants != 0) hash ^= NoParticipants.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Style);
    }
    if (NoParticipants != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoParticipants);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Style);
    }
    if (NoParticipants != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoParticipants);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Distance != global::Distance.Unspecified) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Distance);
    }
    if (Style != global::Style.Unspecified) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Style);
    }
    if (NoParticipants != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoParticipants);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ChallengeDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Distance != global::Distance.Unspecified) {
      Distance = other.Distance;
    }
    if (other.Style != global::Style.Unspecified) {
      Style = other.Style;
    }
    if (other.NoParticipants != 0) {
      NoParticipants = other.NoParticipants;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Distance = (global::Distance) input.ReadEnum();
          break;
        }
        case 24: {
          Style = (global::Style) input.ReadEnum();
          break;
        }
        case 32: {
          NoParticipants = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 16: {
          Distance = (global::Distance) input.ReadEnum();
          break;
        }
        case 24: {
          Style = (global::Style) input.ReadEnum();
          break;
        }
        case 32: {
          NoParticipants = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ParticipantDTO : pb::IMessage<ParticipantDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ParticipantDTO> _parser = new pb::MessageParser<ParticipantDTO>(() => new ParticipantDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ParticipantDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ParticipantDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ParticipantDTO(ParticipantDTO other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    age_ = other.age_;
    challenges_ = other.challenges_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ParticipantDTO Clone() {
    return new ParticipantDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "age" field.</summary>
  public const int AgeFieldNumber = 3;
  private int age_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Age {
    get { return age_; }
    set {
      age_ = value;
    }
  }

  /// <summary>Field number for the "challenges" field.</summary>
  public const int ChallengesFieldNumber = 4;
  private static readonly pb::FieldCodec<global::Challenge> _repeated_challenges_codec
      = pb::FieldCodec.ForMessage(34, global::Challenge.Parser);
  private readonly pbc::RepeatedField<global::Challenge> challenges_ = new pbc::RepeatedField<global::Challenge>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Challenge> Challenges {
    get { return challenges_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ParticipantDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ParticipantDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (Age != other.Age) return false;
    if(!challenges_.Equals(other.challenges_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Age != 0) hash ^= Age.GetHashCode();
    hash ^= challenges_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Age);
    }
    challenges_.WriteTo(output, _repeated_challenges_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Age);
    }
    challenges_.WriteTo(ref output, _repeated_challenges_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Age != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
    }
    size += challenges_.CalculateSize(_repeated_challenges_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ParticipantDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Age != 0) {
      Age = other.Age;
    }
    challenges_.Add(other.challenges_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Age = input.ReadInt32();
          break;
        }
        case 34: {
          challenges_.AddEntriesFrom(input, _repeated_challenges_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Age = input.ReadInt32();
          break;
        }
        case 34: {
          challenges_.AddEntriesFrom(ref input, _repeated_challenges_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    type_ = other.type_;
    username_ = other.username_;
    password_ = other.password_;
    organizer_ = other.organizer_ != null ? other.organizer_.Clone() : null;
    challenge_ = other.challenge_ != null ? other.challenge_.Clone() : null;
    name_ = other.name_;
    age_ = other.age_;
    participant_ = other.participant_ != null ? other.participant_.Clone() : null;
    challenges_ = other.challenges_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Request.Types.Type type_ = global::Request.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Request.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  /// <summary>
  /// finding account
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "organizer" field.</summary>
  public const int OrganizerFieldNumber = 4;
  private global::Organizer organizer_;
  /// <summary>
  /// login
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Organizer Organizer {
    get { return organizer_; }
    set {
      organizer_ = value;
    }
  }

  /// <summary>Field number for the "challenge" field.</summary>
  public const int ChallengeFieldNumber = 5;
  private global::Challenge challenge_;
  /// <summary>
  /// find all challenges
  /// ...
  /// findParticipantsByChallenge
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Challenge Challenge {
    get { return challenge_; }
    set {
      challenge_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 6;
  private string name_ = "";
  /// <summary>
  /// add participant
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "age" field.</summary>
  public const int AgeFieldNumber = 7;
  private int age_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Age {
    get { return age_; }
    set {
      age_ = value;
    }
  }

  /// <summary>Field number for the "participant" field.</summary>
  public const int ParticipantFieldNumber = 8;
  private global::Participant participant_;
  /// <summary>
  /// addParticipantToMoreChallenges
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Participant Participant {
    get { return participant_; }
    set {
      participant_ = value;
    }
  }

  /// <summary>Field number for the "challenges" field.</summary>
  public const int ChallengesFieldNumber = 9;
  private static readonly pb::FieldCodec<global::Challenge> _repeated_challenges_codec
      = pb::FieldCodec.ForMessage(74, global::Challenge.Parser);
  private readonly pbc::RepeatedField<global::Challenge> challenges_ = new pbc::RepeatedField<global::Challenge>();
  /// <summary>
  /// logout
  /// Organizer organizer... [mai sus]
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Challenge> Challenges {
    get { return challenges_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    if (!object.Equals(Organizer, other.Organizer)) return false;
    if (!object.Equals(Challenge, other.Challenge)) return false;
    if (Name != other.Name) return false;
    if (Age != other.Age) return false;
    if (!object.Equals(Participant, other.Participant)) return false;
    if(!challenges_.Equals(other.challenges_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Request.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (organizer_ != null) hash ^= Organizer.GetHashCode();
    if (challenge_ != null) hash ^= Challenge.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Age != 0) hash ^= Age.GetHashCode();
    if (participant_ != null) hash ^= Participant.GetHashCode();
    hash ^= challenges_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::Request.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (organizer_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Organizer);
    }
    if (challenge_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Challenge);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Age);
    }
    if (participant_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Participant);
    }
    challenges_.WriteTo(output, _repeated_challenges_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::Request.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (organizer_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Organizer);
    }
    if (challenge_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Challenge);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Name);
    }
    if (Age != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Age);
    }
    if (participant_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Participant);
    }
    challenges_.WriteTo(ref output, _repeated_challenges_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Request.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (organizer_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Organizer);
    }
    if (challenge_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Challenge);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Age != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
    }
    if (participant_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
    }
    size += challenges_.CalculateSize(_repeated_challenges_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Request.Types.Type.Unknown) {
      Type = other.Type;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    if (other.organizer_ != null) {
      if (organizer_ == null) {
        Organizer = new global::Organizer();
      }
      Organizer.MergeFrom(other.Organizer);
    }
    if (other.challenge_ != null) {
      if (challenge_ == null) {
        Challenge = new global::Challenge();
      }
      Challenge.MergeFrom(other.Challenge);
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Age != 0) {
      Age = other.Age;
    }
    if (other.participant_ != null) {
      if (participant_ == null) {
        Participant = new global::Participant();
      }
      Participant.MergeFrom(other.Participant);
    }
    challenges_.Add(other.challenges_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Request.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
        case 34: {
          if (organizer_ == null) {
            Organizer = new global::Organizer();
          }
          input.ReadMessage(Organizer);
          break;
        }
        case 42: {
          if (challenge_ == null) {
            Challenge = new global::Challenge();
          }
          input.ReadMessage(Challenge);
          break;
        }
        case 50: {
          Name = input.ReadString();
          break;
        }
        case 56: {
          Age = input.ReadInt32();
          break;
        }
        case 66: {
          if (participant_ == null) {
            Participant = new global::Participant();
          }
          input.ReadMessage(Participant);
          break;
        }
        case 74: {
          challenges_.AddEntriesFrom(input, _repeated_challenges_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::Request.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
        case 34: {
          if (organizer_ == null) {
            Organizer = new global::Organizer();
          }
          input.ReadMessage(Organizer);
          break;
        }
        case 42: {
          if (challenge_ == null) {
            Challenge = new global::Challenge();
          }
          input.ReadMessage(Challenge);
          break;
        }
        case 50: {
          Name = input.ReadString();
          break;
        }
        case 56: {
          Age = input.ReadInt32();
          break;
        }
        case 66: {
          if (participant_ == null) {
            Participant = new global::Participant();
          }
          input.ReadMessage(Participant);
          break;
        }
        case 74: {
          challenges_.AddEntriesFrom(ref input, _repeated_challenges_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Request message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("LOGIN")] Login = 1,
      [pbr::OriginalName("LOGOUT")] Logout = 2,
      [pbr::OriginalName("FINDING_ACCOUNT")] FindingAccount = 3,
      [pbr::OriginalName("GET_ALL_CHALLENGES")] GetAllChallenges = 4,
      [pbr::OriginalName("FINDING_ALL_PARTICIPANTS_BY_CHALLENGE")] FindingAllParticipantsByChallenge = 5,
      [pbr::OriginalName("ADD_PARTICIPANT")] AddParticipant = 6,
      [pbr::OriginalName("ADD_PARTICIPANT_TO_MORE_CHALLENGES")] AddParticipantToMoreChallenges = 7,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SwimmingCompetitionProtocolReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    type_ = other.type_;
    organizer_ = other.organizer_ != null ? other.organizer_.Clone() : null;
    challenges_ = other.challenges_.Clone();
    participants_ = other.participants_.Clone();
    participant_ = other.participant_ != null ? other.participant_.Clone() : null;
    error_ = other.error_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Response.Types.Type type_ = global::Response.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Response.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "organizer" field.</summary>
  public const int OrganizerFieldNumber = 2;
  private global::Organizer organizer_;
  /// <summary>
  /// finding account
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Organizer Organizer {
    get { return organizer_; }
    set {
      organizer_ = value;
    }
  }

  /// <summary>Field number for the "challenges" field.</summary>
  public const int ChallengesFieldNumber = 3;
  private static readonly pb::FieldCodec<global::ChallengeDTO> _repeated_challenges_codec
      = pb::FieldCodec.ForMessage(26, global::ChallengeDTO.Parser);
  private readonly pbc::RepeatedField<global::ChallengeDTO> challenges_ = new pbc::RepeatedField<global::ChallengeDTO>();
  /// <summary>
  /// login
  /// ...
  /// find all challenges
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ChallengeDTO> Challenges {
    get { return challenges_; }
  }

  /// <summary>Field number for the "participants" field.</summary>
  public const int ParticipantsFieldNumber = 4;
  private static readonly pb::FieldCodec<global::ParticipantDTO> _repeated_participants_codec
      = pb::FieldCodec.ForMessage(34, global::ParticipantDTO.Parser);
  private readonly pbc::RepeatedField<global::ParticipantDTO> participants_ = new pbc::RepeatedField<global::ParticipantDTO>();
  /// <summary>
  /// findParticipantsByChallenge
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ParticipantDTO> Participants {
    get { return participants_; }
  }

  /// <summary>Field number for the "participant" field.</summary>
  public const int ParticipantFieldNumber = 5;
  private global::Participant participant_;
  /// <summary>
  /// add participant
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Participant Participant {
    get { return participant_; }
    set {
      participant_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 6;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(Organizer, other.Organizer)) return false;
    if(!challenges_.Equals(other.challenges_)) return false;
    if(!participants_.Equals(other.participants_)) return false;
    if (!object.Equals(Participant, other.Participant)) return false;
    if (Error != other.Error) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (organizer_ != null) hash ^= Organizer.GetHashCode();
    hash ^= challenges_.GetHashCode();
    hash ^= participants_.GetHashCode();
    if (participant_ != null) hash ^= Participant.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::Response.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (organizer_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Organizer);
    }
    challenges_.WriteTo(output, _repeated_challenges_codec);
    participants_.WriteTo(output, _repeated_participants_codec);
    if (participant_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Participant);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::Response.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (organizer_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Organizer);
    }
    challenges_.WriteTo(ref output, _repeated_challenges_codec);
    participants_.WriteTo(ref output, _repeated_participants_codec);
    if (participant_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Participant);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Response.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (organizer_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Organizer);
    }
    size += challenges_.CalculateSize(_repeated_challenges_codec);
    size += participants_.CalculateSize(_repeated_participants_codec);
    if (participant_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Response.Types.Type.Unknown) {
      Type = other.Type;
    }
    if (other.organizer_ != null) {
      if (organizer_ == null) {
        Organizer = new global::Organizer();
      }
      Organizer.MergeFrom(other.Organizer);
    }
    challenges_.Add(other.challenges_);
    participants_.Add(other.participants_);
    if (other.participant_ != null) {
      if (participant_ == null) {
        Participant = new global::Participant();
      }
      Participant.MergeFrom(other.Participant);
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Response.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          if (organizer_ == null) {
            Organizer = new global::Organizer();
          }
          input.ReadMessage(Organizer);
          break;
        }
        case 26: {
          challenges_.AddEntriesFrom(input, _repeated_challenges_codec);
          break;
        }
        case 34: {
          participants_.AddEntriesFrom(input, _repeated_participants_codec);
          break;
        }
        case 42: {
          if (participant_ == null) {
            Participant = new global::Participant();
          }
          input.ReadMessage(Participant);
          break;
        }
        case 50: {
          Error = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::Response.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          if (organizer_ == null) {
            Organizer = new global::Organizer();
          }
          input.ReadMessage(Organizer);
          break;
        }
        case 26: {
          challenges_.AddEntriesFrom(ref input, _repeated_challenges_codec);
          break;
        }
        case 34: {
          participants_.AddEntriesFrom(ref input, _repeated_participants_codec);
          break;
        }
        case 42: {
          if (participant_ == null) {
            Participant = new global::Participant();
          }
          input.ReadMessage(Participant);
          break;
        }
        case 50: {
          Error = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Response message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("OK")] Ok = 1,
      [pbr::OriginalName("ERROR")] Error = 2,
      [pbr::OriginalName("FINDING_ACCOUNT")] FindingAccount = 3,
      [pbr::OriginalName("GET_ALL_CHALLENGES")] GetAllChallenges = 4,
      [pbr::OriginalName("FINDING_ALL_PARTICIPANTS_BY_CHALLENGE")] FindingAllParticipantsByChallenge = 5,
      [pbr::OriginalName("ADD_PARTICIPANT")] AddParticipant = 6,
      [pbr::OriginalName("ADD_PARTICIPANT_TO_MORE_CHALLENGES")] AddParticipantToMoreChallenges = 7,
      [pbr::OriginalName("UPDATE_TABLES")] UpdateTables = 8,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
