namespace networking
{
    public enum RequestType
    {
        LOGIN, LOGOUT, FINDING_ACCOUNT, GET_ALL_CHALLENGES, NUMBER_OF_PARTICIPANTS_BY_CHALLENGE,
        FINDING_ALL_PARTICIPANTS_BY_CHALLENGE, FINDING_ALL_CHALENGES_BY_PARTICIPANT,
        ADD_PARTICIPANT, ADD_PARTICIPANT_TO_MORE_CHALLENGES
    }
}