namespace networking
{
    public enum ResponseType
    {
        OK,ERROR,FINDING_ACCOUNT,GET_ALL_CHALLENGES,NUMBER_OF_PARTICIPANTS_BY_CHALLENGE,
        FINDING_ALL_PARTICIPANTS_BY_CHALLENGE, FINDING_ALL_CHALLENGES_BY_PARTICIPANT,
        ADD_PARTICIPANT, ADD_PARTICIPANT_TO_MORE_CHALLENGES,
        UPDATE_TABLES
    }
}